### ISSUE TITLE
Move mbedtls_dev to mbedtls-framework

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls-framework#13]
Move all scripts in `scripts/mbedtls_dev` to `scripts/mbedtls_framework` in mbedtls-framework.

- [ ] In an independent mbedtls PR, rename `mbedtls_dev` to `mbedtls_framework`
- [ ] Move files while keeping their `mbedtls` history (same commits). It has been suggested/discussed to create a commit in mbedtls where all files are removed but the `mbedtls_dev`/`mbedtls_framework` ones and then merge the commit using `git merge --allow-unrelated-histories` to add the files in `mbedtls_framework`. Any issue with that approach? Check that once done with a set of files, it can be done subsequently with other set of files.

**Comment by davidhorstmann-arm** [comment]
I've written a script in Mbed-TLS/mbedtls-docs#145 that should be able to create branches in this way and do the renaming in one step. I'll try applying this to get a PR
