### ISSUE TITLE
Move tests/include/* and /tests/src/* to mbedtls-framework

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls-framework#14]
- [ ] Move `tests/include/*` files from `mbedtls` to `tests/include/` in mbedtls-framework but `tests/include/alt-dummy/*` files. Keep their `mbedtls` history the same way it was done for `mbedtls_dev` script files.
- [ ] Move `tests/src/*` files from `mbedtls` to `tests/src` in mbedtls-framework. Keep their `mbedtls` history the same way it was done for `mbedtls_dev` script files.
- [ ] Adapt make and CMake files
- [ ] Update documentation

**Comment by davidhorstmann-arm** [comment]
Note: This may be blocked by / interfere with #9224, since there is some overlap.
