### ISSUE TITLE
[DI] Move files from scripts to mbedtls-framework

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls-framework#16]
The following table lists the files in scripts/.
Necessary for the split (CI+code_size_compare.py): 2M+3S +7XS ~ 5M
In addition to that: 3S
Open questions:
- Windows build system?
- Do we keep footprint.sh, memory.sh, massif_max.pl and prepare_release.sh?

Table columns legend:
CI: Directly or indirectly necessary to all.sh
F: To be moved to mbedtls-framework (y/n)
C: Used in TF-PSA-Crypto
I: Currently identical between 3.6 and development? (y/n/36/40/-) (36/40 =
present only in that branch, - = no longer present, presumably moved already)
S: Work size for the move and potentially changes needed for TF-PSA-Crypto

| |CI|F|C|I|S|Issue/PR|Comment |
| --- | --- | --- | --- | --- | --- | --- | --- |
| abi_check.py | y | y | y(1.x) | n |S||CI scripts|
| apidoc_full.sh |y|y|y| y |S||called by doxygen.sh, depends on config.py, needs changes for TF-PSA-Crypto|
| assemble_changelog.py |y|y|y| y |XS|[47](https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/47)|adapted to TF-PSA-Crypto|
| code_style.py |y|y|y| n |XS|[48](https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/48)||
| generate_features.pl |y|y|y| n |S| [9420](https://github.com/Mbed-TLS/mbedtls/issues/9420) |Add support for (tf_psa_)crypto_config.h|
| generate_query_config.pl|y|y|y| n |M||adapt to mbedtls_config.h split, adapt to tf_psa_crypto_config.h|
| lcov.sh |y|y|y| y |XS|[41](https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/41) |adapted to TF-PSA-Crypto|
| min_requirements.py |y|y|y| y |XS||CI scripts|
| output_env.sh |y|y|y| y |XS||Called by all.sh, basic-build-test.sh|
| generate_psa_constants.py |y|y|y| n |XS||Called by builds, check-generated-files.sh|
| generate_ssl_debug_helpers.py |y|y|n| y |XS||Called by builds, check-generated-files.sh|
| generate_driver_wrappers.py |y|n|y| n |-||branch specific|
| generate_errors.pl |y|n|n| n |||With #8501 no such script in 4.0 |
| generate_visualc_files.pl |y(4.x?)|n|n| n ||||
| make_generated_files.bat |y(4.x?)|n|n| n ||||
| windows_msbuild.bat |y(4.x?)|n|n| y ||||
| basic.requirements.txt |y|n|y| y |-||branch specific|
| ci.requirements.txt |y|n|y| y |-||branch specific|
| driver.requirements.txt |y|n|y| y |-||branch specific|
| maintainer.requirements.txt |y|n|y| y |-||branch specific|
| config.pl |y(4.x?)|n|n| y |-||Kept in Mbed TLS for backward compatibility|
| config.py |y|n|y| n |-|| branch specific |
||
| bump_version.sh |n|y|y| n |S||adapt to TF-PSA-Crypto|
| code_size_compare.py |n|y|y| n |M||adapt to mbedtls_config.h split, adapt to tf_psa_crypto_config.h|
| ecc-heap.sh |n|y|y| y |S||depends on benchmark.c, adapt to tf_psa_crypto_config.h|
| ecp_comb_table.py |n|n|y| y |-||Utility to add a new curve in ecp_curves.c, tight to ecp_curves.c code|
| footprint.sh |n|y|n| y |||do we keep it? broken, redundant with code_size_compare.py?|
| memory.sh + massif_max.pl |n|y|n| - |||do we keep it? if yes, adapt to mbedtls_config.h split|
| prepare_release.sh |n|y|y| y |?||do we keep it?|
| tmp_ignore_makefiles.sh |n|y|y| y |S||do we keep it? if yes, adapt to TF-PSA-Crypto tree|

**Comment by gilles-peskine-arm** [comment]
`*.requirements.txt` probably should be split differently, with each branch including the framework maintaining requirements for the files that are in that branch. The format supports includes (`-r FILENAME`, I'm not sure if there are restrictions about directories).

`config.pl` is for backward compatibility with existing build scripts in 2.x, we should have removed it in 3.x. It's not official but not clearly unofficial either so we should keep it in 3.6 LTS, but it can go away in `development`.

**Comment by mpg** [comment]
Closing as superseded by #52 and #53 - initially same content, but grouped differently.
