### ISSUE TITLE
Clean up `psasim`

### ISSUE THREAD

**Issue by valeriosetti** [Mbed-TLS/mbedtls-framework#9]
PR https://github.com/Mbed-TLS/mbedtls-framework/pull/8 added `psasim` to this repository, but it didn't add any fix or restyle. The goal of this issue is to cleanup `psasim` to make it usable for the next steps.

**Comment by tom-cosgrove-arm** [comment]
Resolved by merging https://github.com/Mbed-TLS/mbedtls/pull/9097 in the main repo
